//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citador.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class autor
    {
        public autor()
        {
            this.obra = new HashSet<obra>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public string sobrenome { get; set; }
    
        public virtual ICollection<obra> obra { get; set; }
    }
}
