//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citador.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class citacao
    {
        public int id { get; set; }
        public string conteudo { get; set; }
        public int obra_id { get; set; }
    
        public virtual obra obra { get; set; }
    }
}
