//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citador.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class obra
    {
        public obra()
        {
            this.citacao = new HashSet<citacao>();
            this.autor = new HashSet<autor>();
        }
    
        public int id { get; set; }
        public string titulo { get; set; }
        public string editora { get; set; }
        public string local_pub { get; set; }
        public Nullable<System.DateTime> ano_pub { get; set; }
        public Nullable<int> volume { get; set; }
        public Nullable<int> edicao { get; set; }
        public Nullable<int> pag { get; set; }
    
        public virtual ICollection<citacao> citacao { get; set; }
        public virtual ICollection<autor> autor { get; set; }
    }
}
